=== hmcts/cpp-context-material/material-event/material-event-processor/src/yaml/json/schema/public.progression.pet-form-defendant-updated.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://justice.gov.uk/core/courts/pet-form-defendant-updated.json",
  "type": "object",
  "properties": {
    "petId": {
      "description": "Pet Id",
      "$ref": "http://justice.gov.uk/json/schemas/material/data-types.json#/definitions/uuid"
    },
    "caseId": {
      "description": "Case Id",
      "$ref": "http://justice.gov.uk/json/schemas/material/data-types.json#/definitions/uuid"
    },
    "defendantId": {
      "description": "Defendant Id",
      "$ref": "http://justice.gov.uk/json/schemas/material/data-types.json#/definitions/uuid"
    },
    "defendantData": {
      "description": "Defendant data to update",
      "type": "string"
    },
    "updatedBy": {
      "type": "object",
      "properties": {
        "id": {
          "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
        },
        "firstName": {
          "type": "string"
        },
        "lastName": {
          "type": "string"
        },
        "name": {
          "type": "string"
        }
      },
      "oneOf": [
        {
          "required": [
            "id",
            "firstName",
            "lastName"
          ]
        },
        {
          "required": [
            "name"
          ]
        }
      ]
    }
  },
  "required": [
    "petId",
    "caseId",
    "defendantId",
    "defendantData",
    "updatedBy"
  ],
  "additionalProperties": false
}

=== hmcts/cpp-context-material/material-integration-test/src/test/resources/stub-data/received-public-events/public.progression.pet-form-defendant-updated.json
{
  "petId": "PET_ID",
  "caseId": "CASE_ID",
  "defendantId": "DEFENDANT_ID",
  "defendantData": "{\"defendant\":{\"id\": \"DEFENDANT_ID\",\"defenceDynamicFormAnswers\": {\"someField\": true, \"someOtherField\": \"someOtherValue\"}}}",
  "updatedBy": {
    "id": "USER_ID",
    "firstName": "petFormEditorFirstName",
    "lastName": "petFormEditorLastName"
  }
}
