=== hmcts/cpp-context-material/material-event/material-event-processor/src/yaml/json/schema/public.progression.form-created.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://justice.gov.uk/core/courts/form-created.json",
  "type": "object",
  "properties": {
    "courtFormId": {
      "description": "Id",
      "$ref": "http://justice.gov.uk/json/schemas/material/data-types.json#/definitions/uuid"
    },
    "caseId": {
      "description": "Case Id",
      "$ref": "http://justice.gov.uk/json/schemas/material/data-types.json#/definitions/uuid"
    },
    "formId": {
      "description": "Form Id",
      "$ref": "http://justice.gov.uk/json/schemas/material/data-types.json#/definitions/uuid"
    },
    "formDefendants": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "defendantId": {
            "$ref": "http://justice.gov.uk/json/schemas/material/data-types.json#/definitions/uuid"
          }
        },
        "required": [
          "defendantId"
        ],
        "additionalProperties": false
      }
    },
    "formData": {
      "description": "Form Data",
      "type": "string"
    },
    "updatedBy": {
      "type": "object",
      "properties": {
        "id": {
          "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
        },
        "firstName": {
          "type": "string"
        },
        "lastName": {
          "type": "string"
        },
        "name": {
          "type": "string"
        }
      },
      "oneOf": [
        {
          "required": [
            "id",
            "firstName",
            "lastName"
          ]
        },
        {
          "required": [
            "name"
          ]
        }
      ]
    },
    "formType": {
      "description": "Form Type",
      "type": "string",
      "enum": ["BCM", "PET", "PTPH"]
    },
    "submissionId": {
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
    }
  },
  "required": [
    "caseId",
    "courtFormId",
    "formId",
    "formDefendants",
    "formType",
    "updatedBy"
  ],
  "additionalProperties": false
}

=== hmcts/cpp-context-material/material-integration-test/src/test/resources/stub-data/received-public-events/public.progression.form-created.json
{
  "courtFormId": "<COURT_FORM_ID>",
  "caseId": "<CASE_ID>",
  "formId": "<FORM_ID>",
  "formType": "BCM",
  "formDefendants": [
    {
      "defendantId": "<DEFENDANT_ID>"
    }
  ],
  "formData": "{\"id\":\"ID\",\"formId\":\"FORM_ID\",\"caseId\":\"CASE_ID\",\"defendants\":[{\"defendantId\":\"DEFENDANT_ID\",\"offences\":[\"123\",\"321\"]},{\"defendantId\":\"abc\",\"offences\":[\"abc\",\"xyz\"]}],\"data\":{\"prosecution\":{\"witnesses\":[{\"id\":\"qwe\",\"name\":\"BillROGERS\",\"age\":\"01/01/1950\",\"InterpreterRequired\":true,\"defenceDynamicFormAnswers\":{\"witnessGroup\":{\"crossExam\":\"Yes\"}},\"prosecutionDynamicFormAnswers\":{\"witnessGroup\":{\"specialMeasures\":\"Yes\",\"specialMeasuresYesGroup\":{\"specialMeasuresDetail\":\"Achair\"}}}},{\"id\":\"123\",\"caseWitnessId\":\"hgf\",\"defenceDynamicFormAnswers\":{\"witnessGroup\":{\"crossExam\":\"Yes\"}},\"prosecutionDynamicFormAnswers\":{\"witnessGroup\":{\"specialMeasures\":\"Yes\",\"specialMeasuresYesGroup\":{\"specialMeasuresDetail\":\"Achair\"}}}},{\"id\":\"321\",\"caseWitnessId\":\"tds\",\"defenceDynamicFormAnswers\":{\"witnessGroup\":{\"crossExam\":\"Yes\"}},\"prosecutionDynamicFormAnswers\":{\"witnessGroup\":{\"specialMeasures\":\"Yes\",\"specialMeasuresYesGroup\":{\"specialMeasuresDetail\":\"Achair\"}}}}],\"defenceDynamicFormAnswers\":{\"prosecutorGroup\":{\"prosecutorServeEvidence\":\"Yes\",\"prosecutorServeEvidenceYesGroup\":{\"prosecutorServeEvidenceDetails\":\"Servemoreevidenceinfo\"},\"prosecutionCompliance\":\"Yes\",\"prosecutionComplianceYesGroup\":{\"prosecutionComplianceDetailsYes\":\"Undisclosedinfo\"},\"prosecutionComplianceNoGroup\":{\"prosecutionComplianceDetailsNo\":\"\"},\"pendingLinesOfEnquiry\":\"Yes\",\"pendingLinesOfEnquiryYesGroup\":{\"pendingLinesOfEnquiryYesGroup\":\"Pendinginfo\"},\"slaveryOrExploitation\":\"Yes\",\"slaveryOrExploitationYesGroup\":{\"slaveryOrExploitationDetails\":\"Victiminfo\"},\"relyOn\":[\"admissions\",\"cctv\"],\"relyOnAdmissionsGroup\":{\"admissionsDetails\":\"admissioninfo\"},\"relyOnFailureGroup\":{\"failureDetails\":\"\"},\"displayEquipment\":\"Yes\",\"displayEquipmentYesGroup\":{\"displayEquipmentDetails\":\"Displayequipmentinfo\"},\"pointOfLaw\":\"Yes\",\"pointOfLawYesGroup\":{\"pointOfLawDetails\":\"Complexinfo\"}},\"applicationsForDirectionsGroup\":{\"prosecutorWitnessAssistance\":\"Yes\",\"prosecutorWitnessAssistanceYesGroup\":{\"witnessRequiresDetails\":\"\"},\"groundRulesQuestioning\":\"Yes\",\"variationStandardDirections\":\"Yes\",\"variationStandardDirectionsYesGroup\":{\"variationStandardDirectionsYesGroupDetails\":\"Standardtrialinfo\"}}}},\"defence\":{\"defendants\":[{\"id\":\"DEFENDANT_ID\",\"defenceDynamicFormAnswers\":{\"adviceOnPleaAndAbsenceGroup\":{\"creditForGuilty\":\"\",\"defendantUnderstand\":\"\"},\"PresenceGroup\":{\"defendantPresent\":\"Yes\",\"defendantPresentYesGroup\":{\"defendantPresentDetail\":\"Disputeinfo\"},\"defendantInvolvement\":\"Yes\",\"defendantInvolvementYesGroup\":{\"defendantInvolvementYesGroupDetail\":\"Involvementinfo\"},\"anticipatedDefence\":[\"irrelevant\"],\"slaveryOrExploitationGroup\":{\"slaveryOrExploitationGroupText\":\"\"}},\"directionsGroup\":{\"prosecutionWitnessRequires\":\"Yes\",\"prosecutionWitnessRequiresesGroup1\":{\"prosecutionWitnessRequiresesGroup1Details\":\"\"},\"whatAreTheIssues\":\"\",\"whatAreTheIssuesGroup\":{\"explainDispute\":\"Issuesainfo\",\"explainLaw\":\"Issuesbinfo\"}}}},{\"id\":\"abc\",\"dynamicFormData\":{\"adviceOnPleaAndAbsenceGroup\":{\"creditForGuilty\":\"\",\"defendantUnderstand\":\"\"},\"PresenceGroup\":{\"defendantPresent\":\"Yes\",\"defendantPresentYesGroup\":{\"defendantPresentDetail\":\"Disputeinfo\"},\"defendantInvolvement\":\"Yes\",\"defendantInvolvementYesGroup\":{\"defendantInvolvementYesGroupDetail\":\"Involvementinfo\"},\"anticipatedDefence\":[\"irrelevant\"],\"slaveryOrExploitationGroup\":{\"slaveryOrExploitationGroupText\":\"\"}},\"directionsGroup\":{\"prosecutionWitnessRequires\":\"Yes\",\"prosecutionWitnessRequiresesGroup1\":{\"prosecutionWitnessRequiresesGroup1Details\":\"\"},\"whatAreTheIssues\":\"\",\"whatAreTheIssuesGroup\":{\"explainDispute\":\"Issuesainfo\",\"explainLaw\":\"Issuesbinfo\"}}}}],\"witnesses\":[{\"caseWitnessId\":\"UUID\",\"FormProsecutionWitnessId\":\"UUID\",\"isDefendant\":true,\"name\":\"JohnSMITH\",\"age\":\"01/01/1980\",\"InterpreterRequired\":true,\"prosecutionDynamicFormAnswers\":{\"witnessGroup\":{\"crossExam\":\"Yes\"}},\"defenceDynamicFormAnswers\":{\"witnessGroup\":{\"specialMeasures\":\"Yes\",\"specialMeasuresYesGroup\":{\"specialMeasuresDetail\":\"Achair\"}}}},{\"caseWitnessId\":null,\"FormProsecutionWitnessId\":\"UUID\",\"isDefendant\":true,\"name\":\"JamesSAUNDERS\",\"age\":\"01/01/1970\",\"InterpreterRequired\":true,\"prosecutionDynamicFormAnswers\":{\"witnessGroup\":{\"crossExam\":\"Yes\"}},\"defenceDynamicFormAnswers\":{\"witnessGroup\":{\"specialMeasures\":\"Yes\",\"specialMeasuresYesGroup\":{\"specialMeasuresDetail\":\"Achair\"}}}}]}}}",
  "updatedBy": {
    "id" : "<USER_ID>",
    "firstName": "formCreatorFirstName",
    "lastName": "formCreatorLastName"
  }
}
